export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_MAPPER: string =
  "SIGN_IN_WITH_EMAIL_AND_PASSWORD_MAPPER";
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_AUTHENTICATOR: string =
  "SIGN_IN_WITH_EMAIL_AND_PASSWORD_AUTHENTICATOR";
